# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_classify_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(default=None, max_length=16, verbose_name='菜单'),
        ),
    ]
