# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_menu', to='app03.Menu'),
        ),
    ]
