# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0004_auto_20171122_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classify',
            new_name='SiteArticleCategory',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='SiteCategory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_type_id',
        ),
        migrations.AddField(
            model_name='article',
            name='site_article_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app03.SiteArticleCategory'),
        ),
    ]
